#!/usr/bin/env python3
"""
calc_distance.py

State-agnostic, frame-resolved minimum-distance analysis for Amber trajectories.

Design goals
------------
1. Know nothing about protonation/lambda/coupled states.
2. Accept arbitrary CPPTRAJ atom-mask pairs.
3. Emit a canonical long-format per-frame TSV that can be joined to state data.
4. Preserve enough provenance to validate frame <-> MD-step correspondence.
5. Optionally process independent trajectories concurrently with --jobs/--fork.

Example
-------
python3 calc_distance.py \
    -p hewl.parm7 \
    -t 'arex.ph*.nc' \
    --pair E35_D52 ':36@OE1,OE2' ':53@OD1,OD2' \
    --image-anchor '^1' \
    --first-frame-step 510000 \
    --frame-step-interval 10000 \
    -o dyad_min_distance.tsv

The --pair masks are CPPTRAJ/topology masks. Biological-to-topology residue
mapping is intentionally not built into this first vertical slice; a later
selection layer can add residue-centric convenience without changing the
frame-wise output contract.
"""

from __future__ import annotations

import argparse
import csv
from concurrent.futures import ThreadPoolExecutor, as_completed
import glob
import math
import re
import shlex
import subprocess
from pathlib import Path
from typing import Iterable

import numpy as np


def die(msg: str) -> "NoReturn":
    raise RuntimeError(msg)


def natural_key(value: str | Path):
    return [
        int(x) if x.isdigit() else x.lower()
        for x in re.split(r"([0-9]+)", str(value))
    ]


def expand_trajectories(specs: Iterable[str]) -> list[Path]:
    found: dict[str, Path] = {}
    for spec in specs:
        matches = glob.glob(spec)
        if matches:
            for x in matches:
                p = Path(x).resolve()
                if p.is_file():
                    found[str(p)] = p
            continue

        p = Path(spec).resolve()
        if p.is_file():
            found[str(p)] = p
        else:
            raise FileNotFoundError(f"No trajectory matched: {spec}")

    paths = sorted(found.values(), key=natural_key)
    if not paths:
        raise RuntimeError("No trajectory files were found.")
    return paths


def extract_ph(name: str) -> float:
    """
    Accept common AREX naming conventions:
      arex.ph0_5.nc -> 0.5
      arex.ph5_0.nc -> 5.0
      arex_ph7.0.nc -> 7.0
      pH_7.0.nc     -> 7.0
    """
    m = re.search(r"[pP][hH][_=-]?([0-9]+(?:[._][0-9]+)?)", name)
    if not m:
        return math.nan
    return float(m.group(1).replace("_", "."))


def read_numeric(path: Path) -> np.ndarray:
    rows: list[list[float]] = []
    with path.open() as fh:
        for line in fh:
            text = line.strip()
            if not text or text.startswith("#"):
                continue
            fields = text.replace(",", " ").split()
            try:
                vals = [float(x) for x in fields]
            except ValueError:
                continue
            rows.append(vals)

    if not rows:
        return np.empty((0, 0), dtype=float)

    ncol = min(len(r) for r in rows)
    return np.asarray([r[:ncol] for r in rows], dtype=float)


def qmask(mask: str) -> str:
    # CPPTRAJ input is generated by us. Escape only embedded double quotes.
    return '"' + mask.replace('"', r'\"') + '"'


def safe_name(name: str) -> str:
    x = re.sub(r"[^A-Za-z0-9_.-]+", "_", name.strip())
    if not x:
        raise ValueError(f"Invalid empty pair name derived from {name!r}")
    return x


def write_tsv(path: Path, rows: list[dict], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=fields, delimiter="\t", extrasaction="ignore")
        w.writeheader()
        for row in rows:
            out = dict(row)
            for key, val in out.items():
                if isinstance(val, float):
                    out[key] = "" if not math.isfinite(val) else f"{val:.10g}"
            w.writerow(out)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=(
            "Calculate state-agnostic frame-wise minimum distances with CPPTRAJ "
            "and write a canonical long-format TSV."
        )
    )
    p.add_argument("-p", "--topology", type=Path, required=True)
    p.add_argument(
        "-t", "--trajectory", action="append", required=True,
        help="Trajectory path or glob; may be repeated. Quote shell globs."
    )
    p.add_argument(
        "--pair", action="append", nargs=3, required=True,
        metavar=("NAME", "MASK1", "MASK2"),
        help=(
            "Minimum-distance observable: NAME MASK1 MASK2. May be repeated. "
            "Masks use CPPTRAJ/topology numbering."
        ),
    )
    p.add_argument(
        "--image-anchor", default=None,
        help="Optional CPPTRAJ autoimage anchor mask, e.g. '^1'."
    )
    p.add_argument("--start", type=int, default=1)
    p.add_argument("--stop", default="last")
    p.add_argument("--stride", type=int, default=1)

    p.add_argument(
        "--first-frame-step", type=int, default=None,
        help="Absolute MD step corresponding to stored trajectory frame 1."
    )
    p.add_argument(
        "--frame-step-interval", type=int, default=None,
        help="MD-step spacing between consecutive stored trajectory frames."
    )

    p.add_argument("--cpptraj", default="cpptraj")
    p.add_argument(
        "-j", "--jobs", "--fork",
        dest="jobs",
        type=int,
        default=1,
        metavar="N",
        help=(
            "Number of trajectories to process concurrently using independent "
            "CPPTRAJ processes (default: 1). --fork is an alias for --jobs."
        ),
    )
    p.add_argument(
        "--workdir", type=Path, default=Path("distance_work"),
        help="CPPTRAJ inputs/logs/intermediate series."
    )
    p.add_argument("-o", "--output", type=Path, default=Path("distance_frames.tsv"))
    p.add_argument("--force", action="store_true")
    return p.parse_args()


def validate_args(args: argparse.Namespace) -> None:
    if not args.topology.is_file():
        raise FileNotFoundError(args.topology)
    if args.start < 1:
        raise ValueError("--start must be >= 1")
    if args.stride < 1:
        raise ValueError("--stride must be >= 1")
    if args.jobs < 1:
        raise ValueError("--jobs/--fork must be >= 1")
    if args.stop != "last":
        try:
            stop = int(args.stop)
        except ValueError as exc:
            raise ValueError("--stop must be a positive integer or 'last'") from exc
        if stop < 1:
            raise ValueError("--stop must be a positive integer or 'last'")

    one = args.first_frame_step is not None
    two = args.frame_step_interval is not None
    if one != two:
        raise ValueError(
            "--first-frame-step and --frame-step-interval must be supplied together"
        )
    if two and args.frame_step_interval <= 0:
        raise ValueError("--frame-step-interval must be > 0")

    names = [safe_name(x[0]) for x in args.pair]
    if len(names) != len(set(names)):
        raise ValueError("Pair NAME values must be unique.")


def run_one_trajectory(
    args: argparse.Namespace,
    traj: Path,
    pairs: list[tuple[str, str, str]],
) -> dict[str, np.ndarray]:
    label = traj.stem
    run_dir = args.workdir / label
    run_dir.mkdir(parents=True, exist_ok=True)

    outputs: dict[str, Path] = {}
    lines = [
        f'parm "{args.topology.resolve()}"',
        f'trajin "{traj.resolve()}" {args.start} {args.stop} {args.stride}',
    ]

    if args.image_anchor:
        lines.append(f"autoimage anchor {qmask(args.image_anchor)}")

    for name, mask1, mask2 in pairs:
        out = run_dir / f"{safe_name(name)}.dat"
        outputs[name] = out
        # "byatom" gives the minimum atom-atom distance between the two masks.
        lines.extend([
            "mindist \\",
            f"    mask1 {qmask(mask1)} \\",
            f"    mask2 {qmask(mask2)} \\",
            "    byatom \\",
            f"    name {safe_name(name)} \\",
            f'    out "{out.resolve()}"',
        ])

    lines.extend(["run", "quit", ""])
    inp = run_dir / "distance.in"
    log = run_dir / "cpptraj.log"
    inp.write_text("\n".join(lines))

    need_run = args.force or any(not p.exists() for p in outputs.values())
    if need_run:
        with log.open("w") as fh:
            proc = subprocess.run(
                [args.cpptraj, "-i", str(inp)],
                stdout=fh,
                stderr=subprocess.STDOUT,
            )
        if proc.returncode != 0:
            raise RuntimeError(
                f"CPPTRAJ failed for {traj.name}; see {log}"
            )

    result: dict[str, np.ndarray] = {}
    counts: dict[str, int] = {}
    for name, path in outputs.items():
        if not path.exists():
            raise RuntimeError(f"Expected CPPTRAJ output not found: {path}")
        arr = read_numeric(path)
        if arr.ndim != 2 or arr.shape[1] < 2:
            raise RuntimeError(f"Could not read distance series from {path}")
        vals = np.asarray(arr[:, 1], dtype=float)
        if np.any(~np.isfinite(vals)):
            raise RuntimeError(f"Non-finite distances found in {path}")
        if np.any(vals < -1.0e-8):
            raise RuntimeError(f"Negative distances found in {path}")
        result[name] = vals
        counts[name] = len(vals)

    if len(set(counts.values())) != 1:
        details = ", ".join(f"{k}={v}" for k, v in sorted(counts.items()))
        raise RuntimeError(
            f"Inconsistent frame counts for {traj.name}: {details}"
        )

    return result


def main() -> None:
    args = parse_args()
    validate_args(args)
    trajectories = expand_trajectories(args.trajectory)
    args.workdir.mkdir(parents=True, exist_ok=True)

    # One trajectory label maps to one work directory and one namespace in the
    # final TSV. Reject ambiguous inputs rather than allowing two trajectories
    # with the same stem to overwrite each other's intermediate files.
    labels = [traj.stem for traj in trajectories]
    if len(labels) != len(set(labels)):
        duplicates = sorted(
            label for label in set(labels) if labels.count(label) > 1
        )
        raise RuntimeError(
            "Trajectory filename stems must be unique because each stem is used "
            "as the trajectory label and work-directory name. Duplicate stem(s): "
            + ", ".join(duplicates)
        )

    pairs = [(safe_name(n), m1, m2) for n, m1, m2 in args.pair]
    pair_lookup = {name: (mask1, mask2) for name, mask1, mask2 in pairs}

    # Calculate each trajectory independently. ThreadPoolExecutor is used only
    # as a lightweight launcher/waiter for external CPPTRAJ processes; the
    # numerical work remains in separate CPPTRAJ processes.
    results: dict[Path, dict[str, np.ndarray]] = {}
    failures: list[tuple[Path, BaseException]] = []
    workers = min(args.jobs, len(trajectories))

    if workers == 1:
        for traj in trajectories:
            label = traj.stem
            print(f"[{label}] running")
            try:
                results[traj] = run_one_trajectory(args, traj, pairs)
            except BaseException as exc:
                failures.append((traj, exc))
                break
            print(f"[{label}] complete")
    else:
        print(
            f"Processing {len(trajectories)} trajectories with "
            f"{workers} concurrent CPPTRAJ jobs."
        )
        with ThreadPoolExecutor(max_workers=workers) as executor:
            future_to_traj = {
                executor.submit(
                    run_one_trajectory,
                    args,
                    traj,
                    pairs,
                ): traj
                for traj in trajectories
            }

            for future in as_completed(future_to_traj):
                traj = future_to_traj[future]
                label = traj.stem
                try:
                    results[traj] = future.result()
                except BaseException as exc:
                    failures.append((traj, exc))
                    print(f"[{label}] FAILED")
                else:
                    print(f"[{label}] complete")

    # Never write a combined table that could be mistaken for a complete
    # analysis if one or more trajectory jobs failed.
    if failures:
        details = "\n".join(
            f"  {traj}: {type(exc).__name__}: {exc}"
            for traj, exc in failures
        )
        raise RuntimeError(
            f"{len(failures)} trajectory job(s) failed; combined output was "
            f"not written:\n{details}"
        )

    rows: list[dict] = []

    # Assemble rows only after all jobs have succeeded and always iterate the
    # original naturally sorted trajectory list. Therefore --jobs changes only
    # execution concurrency, never the ordering of the final TSV.
    for traj in trajectories:
        label = traj.stem
        ph = extract_ph(label)
        series = results[traj]

        nframes = len(next(iter(series.values())))
        for i in range(nframes):
            analysis_row = i + 1
            trajectory_frame = args.start + i * args.stride

            if args.first_frame_step is None:
                step = ""
            else:
                step = (
                    args.first_frame_step
                    + (trajectory_frame - 1) * args.frame_step_interval
                )

            for name, values in series.items():
                mask1, mask2 = pair_lookup[name]
                rows.append({
                    "trajectory": label,
                    "pH": ph,
                    "analysis_row": analysis_row,
                    "trajectory_frame": trajectory_frame,
                    "step": step,
                    "observable": name,
                    "metric": "min_distance",
                    "selection1": mask1,
                    "selection2": mask2,
                    "value": float(values[i]),
                    "unit": "A",
                })

    fields = [
        "trajectory",
        "pH",
        "analysis_row",
        "trajectory_frame",
        "step",
        "observable",
        "metric",
        "selection1",
        "selection2",
        "value",
        "unit",
    ]
    write_tsv(args.output, rows, fields)

    settings = args.output.with_suffix(args.output.suffix + ".settings.txt")
    with settings.open("w") as fh:
        fh.write(f"topology={args.topology.resolve()}\n")
        fh.write("trajectories=" + ",".join(str(x) for x in trajectories) + "\n")
        fh.write(f"start={args.start}\n")
        fh.write(f"stop={args.stop}\n")
        fh.write(f"stride={args.stride}\n")
        fh.write(f"first_frame_step={args.first_frame_step}\n")
        fh.write(f"frame_step_interval={args.frame_step_interval}\n")
        fh.write(f"image_anchor={args.image_anchor}\n")
        fh.write(f"cpptraj={args.cpptraj}\n")
        fh.write(f"jobs={args.jobs}\n")
        for name, mask1, mask2 in pairs:
            fh.write(f"pair.{name}.mask1={mask1}\n")
            fh.write(f"pair.{name}.mask2={mask2}\n")

    print(f"Wrote {args.output}")
    print(f"Wrote {settings}")


if __name__ == "__main__":
    main()
